### ISSUE TITLE
create_tx is no longer working in the latest release, it works on 1.0.2.

### ISSUE THREAD

**Issue by unl1k3ly** [terra-money/terra.py#77]
Hi. 

I'm not sure if it's only me but due recent updates in terra.py my `create_tx` I used to simulate fees against the node is no longer working.

This code works below works on `1.0.2` but won't work on the latest. Error message I get is: `TypeError: create_and_sign_tx() got an unexpected keyword argument 'msgs'` when building `tx` using `create_tx`. 

```python
    def execute_contract_msg(self, contract_addr):

        mk = MnemonicKey(mnemonic='')
        simulation_wallet = self.terra.wallet(mk)
        msg = {count: {}}  
        try:
            execute = MsgExecuteContract(
                sender=simulation_wallet.key.acc_address,
                contract=contract_addr,
                execute_msg=msg,
                coins=Coins(),
            )

            tx = simulation_wallet.create_tx(
                msgs=[execute],
                fee_denoms=['uusd'],
                memo=".",
            )
            print(tx)

```

**Comment by Vritra4** [comment]
there are some breaking changes for terra.py 2.0.0.
we have to use CreateTxOptions() now.
```
from terra_sdk.client.lcd.api.tx import CreateTxOptions
...
tx_opt = CreateTxOptions(msgs=[execute], fee_denoms=['uusd'], memo=".")
tx = simulation_wallet.create_tx(tx_opt)
...
```

**Comment by unl1k3ly** [comment]
Thank you @Vritra4 !
